### ISSUE TITLE
Code for api missing

### ISSUE THREAD

**Issue by edchelstephens** [RolandGuijt/ps-react-fundamentals#6]
Hi @RolandGuijt,

I'm following thru your course and I'm at "Effects and Re-rendering" section:

I am coding along and I have a problem.

I'm trying to learn the useEffect with the api call:

useEffect(()=>{
        const fetchHouses = async () => {
            const response = await fetch("/api/houses");
            const houses = await response.json();
            setHouses(houses);
        }
        fetchHouses();
    })
    
    
But I don't have the see the files for the pages/api/houses?

Can you please add them? If it is already there, can you point me where it is?

This is my first time with Next.js so I don't know what to do.

I'm puzzled that I can't find the api/houses/code for the "/api/houses" request.

I want to continue following along and I do it my coding along, step by step.

![image](https://github.com/RolandGuijt/ps-react-fundamentals/assets/49672830/d5d868da-70c0-4345-aba9-0a3023b138e9)

**Comment by RolandGuijt** [comment]
Hi,

Please take a look at the different branches available in the repo.

**Comment by edchelstephens** [comment]
Thanks @RolandGuijt , got it! :)

It was in the RenderingSideEffects branch.
